on:
  pull_request:
    types: [opened, synchronize]
    branches:
    - main

name: Pull Request updated

jobs:
  history:
    name: Pull Request Body
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Body
        uses: technote-space/pr-commit-body-action@v1
